[settings]
disable_tools = ["node"]

[tools]
"ubi:EmmyLuaLs/emmylua-analyzer-rust" = { version = "0.18.0", exe = "emmylua_ls", matching_regex = "^emmylua_ls" }

# small sample application that can be installed with mise and used in the test
# environment
cowsay = "latest"
