
[tools]

# small sample application that can be installed with mise and used in the test
# environment
cowsay = "latest"
"ubi:EmmyLuaLs/emmylua-analyzer-rust" = { version = "0.14.0", exe = "emmylua_ls", matching_regex = "^emmylua_ls" }
actionlint = "1.7.7"
